"""add stage.sucessful

Revision ID: 496b7c120f44
Revises: None
Create Date: 2014-01-09 21:43:52.310513

"""

# revision identifiers, used by Alembic.
revision = '496b7c120f44'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage', 'successful',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default='False')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stage', 'successful',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default='False')
    ### end Alembic commands ###
