"""add task.must_succeed

Revision ID: d45519790b6
Revises: None
Create Date: 2014-01-14 17:58:43.666601

"""

# revision identifiers, used by Alembic.
revision = 'd45519790b6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('must_succeed', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'must_succeed')
    ### end Alembic commands ###
